name: Create PR which updates sha and shallow_since in `git_repository` bazel rule

# on:
#   # Run this workflow every minute.
#   schedule:
#     - cron: "0/15 * * * *"
#   workflow_dispatch:

on:
  workflow_call:
    inputs:
      script_directory:
        required: true
        type: string
      current_commit:
        required: true
        type: string
      current_shallow_since:  
        required: true
        type: string
    secrets:
      main_lib_pr_bot_secret:
        required: true

# jobs:
#   create-PR:
#     uses: ArthurBandaryk/main-lib/.github/workflows/update-main-lib-remote.yml@main
#     with:
#       script_directory: dev-tools
#     secrets:
#       pr_bot_secret: ${{ secrets.pr_bot_secret }}

jobs:
  Try-Update-Eventuals:
    runs-on: ubuntu-latest
    steps:
      - name: Install buildifier for .bzl files
        run: brew install buildifier
        shell: bash

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.main_lib_pr_bot_secret }}

      - name: Update WORKSPACE.bazel
        run: |
          script_path=.github/workflows/scripts/update-eventuals-git-repository.sh
          chmod +x ${{inputs.script_directory}}/${script_path}
          ${{ inputs.script_directory }}/${script_path} \
          WORKSPACE.bazel ${{ inputs.current_commit }} \
          ${{ inputs.current_shallow_since }}
        shell: bash  

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update eventuals in git_repository bazel rule
          title: Update WORKSPACE.bazel
          body: Update eventuals commit and shallow_since in 'git_repository' bazel rule
          branch: update-eventuals
          base: main
          add-paths: WORKSPACE.bazel
          token: ${{ secrets.main_lib_pr_bot_secret }}
